INSERT INTO news_list (title, media, url) VALUES ('경찰, 동거 중인 60대 여성 살해한 50대男 체포', '파이낸셜뉴스', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=014&aid=0004560560');
INSERT INTO news_list (title, media, url) VALUES ('경찰 간부가 금은방 털었다 "CCTV 피할 동선도 짜며 치밀"', '중앙일보', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=025&aid=0003067738');
INSERT INTO news_list (title, media, url) VALUES ('제주신화월드 카지노에서 145억 원 도난...경찰 수사', 'YTN', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=052&aid=0001535024');
INSERT INTO news_list (title, media, url) VALUES ('경찰청장 "정인이 사건 수사 미흡" 사과...양천서장 대기발령 [전문]', '중앙일보', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=025&aid=0003067516');
INSERT INTO news_list (title, media, url) VALUES ('경찰 간부, 방역수칙 어기고 노래방서 지인들과 "술판"', 'TV조선', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=448&aid=0000315778');
INSERT INTO news_list (title, media, url) VALUES ('"학대신고 3번이면 구속"…7년 전 경찰 대책은 어디로?', '노컷뉴스', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=079&aid=0003451939');
INSERT INTO news_list (title, media, url) VALUES ('여야, "정인이 사건" 경찰 질타…"수사·기소권 분리가 맞나"(종합)', '뉴시스', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=100&oid=003&aid=0010282898');
INSERT INTO news_list (title, media, url) VALUES ('“정인이 멍 외면한 홀트·아동기관…양모 위로한 경찰”', '국민일보', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=005&aid=0001398543');
INSERT INTO news_list (title, media, url) VALUES ('경찰청장, "정인이 사건" 대국민 사과…"양천서장 대기발령"', 'SBS', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=055&aid=0000865928');
INSERT INTO news_list (title, media, url) VALUES ('김창룡 청장, "정인이 사건 검찰 송치...경찰 재수사 어려워"', '서울경제', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=011&aid=0003853144');
INSERT INTO news_list (title, media, url) VALUES ('아동학대 전담 경찰에 인센티브 늘린다', '서울경제', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=011&aid=0003852881');
INSERT INTO news_list (title, media, url) VALUES ('금은방 털이한 현직 경찰관…범행 20일 만에 체포', '노컷뉴스', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=079&aid=0003452049');
INSERT INTO news_list (title, media, url) VALUES ('BJ땡초, 지적장애 여성 "벗방" 논란… 경찰 긴급 체포', '조선비즈', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=366&aid=0000647560');
INSERT INTO news_list (title, media, url) VALUES ('경찰청장 ‘정인이 사건’ 공식 사과…양천서장 대기발령', '경향신문', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=032&aid=0003052653');
INSERT INTO news_list (title, media, url) VALUES ('"정인이 사건" 경찰청장 대국민 사과...양천서장 대기발령', 'YTN', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=052&aid=0001535032');
INSERT INTO news_list (title, media, url) VALUES ('[인사] 경찰청', '연합뉴스', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=001&aid=0012125860');
INSERT INTO news_list (title, media, url) VALUES ('광주 금은방 절도범은 현직 경찰…20일 만에 검거', '연합뉴스TV', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=422&aid=0000465351');
INSERT INTO news_list (title, media, url) VALUES ('트럼프 지지자들 침입 미 의사당 전격봉쇄…경찰과 대치', '디지털타임스', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=104&oid=029&aid=0002647434');
INSERT INTO news_list (title, media, url) VALUES ('"신고 묵살" 경찰 질타…중대재해법 "초읽기"', 'MBC', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=100&oid=214&aid=0001091245');
INSERT INTO news_list (title, media, url) VALUES ('"베테랑 경찰 금은방 털이" 완전 범죄를 꿈꿨다…버젓이 출근도(종합)', '연합뉴스', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=001&aid=0012126451');
INSERT INTO news_list (title, media, url) VALUES ('고개숙인 경찰청장', '국민일보', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=100&oid=005&aid=0001398694');
INSERT INTO news_list (title, media, url) VALUES ('충북 경찰 4년 연속 총경 2명 배출', '뉴스1', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=421&aid=0005094372');
INSERT INTO news_list (title, media, url) VALUES ('경찰, 신도들 성 착취 의혹 목사 구속영장 신청', '연합뉴스', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=001&aid=0012126268');
INSERT INTO news_list (title, media, url) VALUES ('미 검찰, 흑인에게 7발 총쏜 경찰에 ‘면죄부’…항의 시위 불붙나', '한겨레', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=104&oid=028&aid=0002527404');
INSERT INTO news_list (title, media, url) VALUES ('경찰, "정인이 학대" 세 차례 신고에도 "혐의 없음" 이유는', '이데일리', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=018&aid=0004823885');
INSERT INTO news_list (title, media, url) VALUES ('美 의회서 여성 1명 가슴에 총 맞아 중태···경찰관들 부상 (종합)', '서울경제', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=104&oid=011&aid=0003852602');
INSERT INTO news_list (title, media, url) VALUES ('[인사] 경찰청', '연합뉴스', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=001&aid=0012122542');
INSERT INTO news_list (title, media, url) VALUES ('사라진 145억원…제주경찰, 50대 여직원 행방 추적중', '노컷뉴스', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=079&aid=0003452109');
INSERT INTO news_list (title, media, url) VALUES ('"정인이 사망" 결국 고개 숙인 경찰청장…"재발 막겠다"(종합)', '뉴시스', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=003&aid=0010280557');
INSERT INTO news_list (title, media, url) VALUES ('광주전남 "경찰의 꽃" 총경 7명 승진', '노컷뉴스', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=079&aid=0003452330');
INSERT INTO news_list (title, media, url) VALUES ('정인이 멍이 몽고반점인줄...경찰청장 "보호자 말 너무 믿었다"', '중앙일보', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=025&aid=0003067857');
INSERT INTO news_list (title, media, url) VALUES ('[N디데이] 이원근, 의무경찰 마치고 오늘 전역', '뉴스1', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=106&oid=421&aid=0005092738');
INSERT INTO news_list (title, media, url) VALUES ('경찰청장 "새로운 증거 없인 양부모 살인죄 적용 어렵다"', 'YTN', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=100&oid=052&aid=0001535454');
INSERT INTO news_list (title, media, url) VALUES ('"정인이 사건" 경찰들 한숨…"잘못했지만 제도도 미비"', '뉴시스', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=003&aid=0010282338');
INSERT INTO news_list (title, media, url) VALUES ('경찰, "윤석열 응원 화환" 방화 70대에 구속영장 신청', '조선비즈', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=366&aid=0000647579');
INSERT INTO news_list (title, media, url) VALUES ('여야, 경찰청장 불러 "정인이 사건" 긴급질의', '연합뉴스TV', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=100&oid=422&aid=0000465308');
INSERT INTO news_list (title, media, url) VALUES ('미 경찰 "국회의사당 구내서 4명 사망…52명 체포"', '뉴스1', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=104&oid=421&aid=0005094290');
INSERT INTO news_list (title, media, url) VALUES ('“정인이 사건 방조한 경찰 파면하라” 靑청원 20만 돌파', '국민일보', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=005&aid=0001398077');
INSERT INTO news_list (title, media, url) VALUES ('장흥군, 코로나19 예방 위한 "자치경찰 TF팀" 시범운영', '뉴스1', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=421&aid=0005093478');
INSERT INTO news_list (title, media, url) VALUES ('美경찰 "의회 난입사태로 4명 사망…52명 체포"', '이데일리', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=104&oid=018&aid=0004823582');
INSERT INTO news_list (title, media, url) VALUES ('아동학대 신고에 "훈계했네"라고 뭉갠 경찰…국회 보고서는 이미 작년에 경고', '조선비즈', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=100&oid=366&aid=0000647599');
INSERT INTO news_list (title, media, url) VALUES ('정인이 못 살린 양천경찰서만 그럴까?…"경찰과 협조 안돼"', '뉴스1', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=421&aid=0005090280');
INSERT INTO news_list (title, media, url) VALUES ('지적장애女 강제추행 방송한 BJ..경찰, 긴급체포', '파이낸셜뉴스', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=014&aid=0004560417');
INSERT INTO news_list (title, media, url) VALUES ('부산경찰청, 경무관 승진자 2명 첫 배출', 'KBS', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=056&aid=0010966740');
INSERT INTO news_list (title, media, url) VALUES ('울산경찰청 원용덕·양순봉 계장 총경 승진', '노컷뉴스', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=079&aid=0003452357');
INSERT INTO news_list (title, media, url) VALUES ('인사하는 김창룡 경찰청장', '뉴시스', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=100&oid=003&aid=0010282010');
INSERT INTO news_list (title, media, url) VALUES ('김창룡 경찰청장 “정인이 사건 수사미흡 깊이 사죄”', '동아일보', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=020&aid=0003330779');
INSERT INTO news_list (title, media, url) VALUES ('“정인이 사건이 입양 문제냐”...경찰 대응 질타한 행안위', '서울신문', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=100&oid=081&aid=0003154021');
INSERT INTO news_list (title, media, url) VALUES ('인천서 40대 남성 친형 살해하고 경찰에 자수', '연합뉴스TV', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=422&aid=0000465227');
INSERT INTO news_list (title, media, url) VALUES ('홍콩 경찰, 홍콩보안법 위반 혐의로 50여 명 무더기 체포', '서울경제', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=104&oid=011&aid=0003852411');
INSERT INTO news_list (title, media, url) VALUES ('광주 경찰관 금은방 절도', '뉴시스', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=003&aid=0010282883');
INSERT INTO news_list (title, media, url) VALUES ('국회서 또 고개숙인 김창룡.. "경찰 최고 책임자로서 깊은 책임느껴"', '파이낸셜뉴스', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=100&oid=014&aid=0004560648');
INSERT INTO news_list (title, media, url) VALUES ('경찰, "윤석열 응원 화환" 불지른 70대 영장 신청', '이데일리', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=018&aid=0004822969');
INSERT INTO news_list (title, media, url) VALUES ('정인이‧이용구‧박원순까지 "부실"…안개 낀 경찰의 "책임수사"', '노컷뉴스', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=079&aid=0003451366');
INSERT INTO news_list (title, media, url) VALUES ('경찰, 지적장애 여성 성추행한 BJ 긴급체포', 'SBS', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=055&aid=0000865964');
INSERT INTO news_list (title, media, url) VALUES ('美 동포 2세, LA경찰국 서열 2위 수석부국장 승진', '연합뉴스', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=100&oid=001&aid=0012124555');
INSERT INTO news_list (title, media, url) VALUES ('홍콩 경찰, 범민주 인사 53명 체포', '경향신문', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=104&oid=032&aid=0003052712');
INSERT INTO news_list (title, media, url) VALUES ('경찰·주방위군 미 연방의사당 안전확보, 상하원 합동회의 속개', '오마이뉴스', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=104&oid=047&aid=0002297966');
INSERT INTO news_list (title, media, url) VALUES ('경찰, 울진군의회 의장 사무실 등 압수수색…뇌물수수 의혹', '연합뉴스', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=001&aid=0012122907');
INSERT INTO news_list (title, media, url) VALUES ('마스크 쓰고 턴 뒤, 번호판 가리고 달아났다...그는 현직 경찰', '조선일보', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=023&aid=0003588322');
INSERT INTO news_list (title, media, url) VALUES ('이원근, 오늘(7일) 의무 경찰 복무 마치고 전역', '마이데일리', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=106&oid=117&aid=0003450735');
INSERT INTO news_list (title, media, url) VALUES ('당정, 아동학대 현장 경찰 출입·조사권 확대…긴급대책 내주 발표', '뉴스1', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=100&oid=421&aid=0005093451');
INSERT INTO news_list (title, media, url) VALUES ('경찰, "영진약품 부당합병 의혹" KT&G 압수수색', 'MBC', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=214&aid=0001090939');
INSERT INTO news_list (title, media, url) VALUES ('금은방·금고털이에 토막살인까지…"범인은 경찰이었다"', '연합뉴스', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=001&aid=0012126603');
INSERT INTO news_list (title, media, url) VALUES ('경찰, 의회서 트럼프 지지자들과 권총 대치···시위대 유리창 깨고 남부연합기 흔들어', '서울경제', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=101&oid=011&aid=0003852608');
INSERT INTO news_list (title, media, url) VALUES ('전주 한 사립고 기간제 교사 "답안지 조작" 의혹..경찰 수사', '파이낸셜뉴스', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=014&aid=0004559540');
INSERT INTO news_list (title, media, url) VALUES ('신화월드 카지노 횡령 사건, 제주경찰청이 수사', 'MBC', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=214&aid=0001091205');
INSERT INTO news_list (title, media, url) VALUES ('술취한 무면허 10대 운전하다 사고…경찰 입건"', '연합뉴스TV', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=422&aid=0000465174');
INSERT INTO news_list (title, media, url) VALUES ('"정인이" 사망 한달전 경찰신고 보니…"혼자서 못걸어"', '뉴시스', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=003&aid=0010279882');
INSERT INTO news_list (title, media, url) VALUES ('박범계, 주폭에 "경찰 탓" 돌렸는데···정인 양 어찌 위할 수 있나', '서울경제', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=100&oid=011&aid=0003852594');
INSERT INTO news_list (title, media, url) VALUES ('"차에 개 매달고 5km 주행" 50대 경찰 조사', 'YTN', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=052&aid=0001534308');
INSERT INTO news_list (title, media, url) VALUES ('미 경찰, 의회 의사당 건물 탈환...20명 검거', '파이낸셜뉴스', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=104&oid=014&aid=0004560362');
INSERT INTO news_list (title, media, url) VALUES ('사과 또 사과…국회 불려간 경찰청장, "정인이 사건"에 뭇매', '이데일리', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=018&aid=0004823541');
INSERT INTO news_list (title, media, url) VALUES ('트럼프 지지 시위대 의사당 난입 4명 사망…경찰 "52명 체포"', '디지털타임스', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=104&oid=029&aid=0002647533');
INSERT INTO news_list (title, media, url) VALUES ('경찰, "여고생 집단 성폭행" 또래 남학생 3명 구속영장 신청', '더팩트', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=629&aid=0000061620');
INSERT INTO news_list (title, media, url) VALUES ('차에서 내린 시민들..."제설도 경찰 도움도 없었다"', 'YTN', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=052&aid=0001535124');
INSERT INTO news_list (title, media, url) VALUES ('충북경찰청 최기영 수사과장 경무관 승진', '뉴시스', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=003&aid=0010279561');
INSERT INTO news_list (title, media, url) VALUES ('“정인양 사건 수사 부실” 경찰청장 뒤늦게 대국민사과', '세계일보', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=022&aid=0003540287');
INSERT INTO news_list (title, media, url) VALUES ('경찰, 인터넷 방송서 장애여성 추행 혐의 BJ 2명 또 긴급체포', '뉴시스', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=003&aid=0010282924');
INSERT INTO news_list (title, media, url) VALUES ('김광식 경찰청 홍보담당관 등 37명 경무관 승진(종합)', '연합뉴스', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=001&aid=0012122609');
INSERT INTO news_list (title, media, url) VALUES ('"정인이 생명 보호하지 못했다"…경찰청장 사과', 'MBC', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=214&aid=0001090984');
INSERT INTO news_list (title, media, url) VALUES ('경찰 "영진약품 부당합병" 의혹 KT＆G 본사 압수수색', '연합뉴스', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=001&aid=0012123738');
INSERT INTO news_list (title, media, url) VALUES ('국회 행안위, 오늘 "정인이 사건" 긴급질의…경찰청장 출석', '스포츠서울', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=468&aid=0000731152');
INSERT INTO news_list (title, media, url) VALUES ('김포경찰서 경찰관 1명 코로나19 확진…청사 임시 폐쇄', '연합뉴스', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=001&aid=0012123331');
INSERT INTO news_list (title, media, url) VALUES ('김창룡 경찰청장 "현장 경찰관의 학대징후 판단력 키우겠다"', '파이낸셜뉴스', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=100&oid=014&aid=0004560628');
INSERT INTO news_list (title, media, url) VALUES ('경찰청장 "새로운 증거 없인 양부모 살인죄 적용 어렵다"', 'YTN', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=100&oid=052&aid=0001535454');
INSERT INTO news_list (title, media, url) VALUES ('"수사 미흡했다"…경찰청장 사과에 양천서장은 대기발령', 'MBN', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=057&aid=0001536426');
INSERT INTO news_list (title, media, url) VALUES ('경찰, 총경 107명 승진…사상 첫 여성 두자릿수 선발', '뉴시스', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=003&aid=0010282179');
INSERT INTO news_list (title, media, url) VALUES ('"정인이 사건" 경찰들 한숨…"잘못했지만 제도도 미비"', '뉴시스', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=003&aid=0010282338');
INSERT INTO news_list (title, media, url) VALUES ('경찰, "윤석열 응원 화환" 방화 70대에 구속영장 신청', '조선비즈', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=366&aid=0000647579');
INSERT INTO news_list (title, media, url) VALUES ('특별방역기간 불 꺼진 노래방서 술판 벌인 경찰 간부', 'MBN', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=057&aid=0001536639');
INSERT INTO news_list (title, media, url) VALUES ('경찰청장 ""정인이 사건" 대응 미흡"…양천서장 대기발령', '세계일보', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=102&oid=022&aid=0003540125');
INSERT INTO news_list (title, media, url) VALUES ('여야, 경찰청장 불러 "정인이 사건" 긴급질의', '연합뉴스TV', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=100&oid=422&aid=0000465308');
INSERT INTO news_list (title, media, url) VALUES ('미 경찰 "국회의사당 구내서 4명 사망…52명 체포"', '뉴스1', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=104&oid=421&aid=0005094290');
INSERT INTO news_list (title, media, url) VALUES ('미 경찰 "국회의사당 구내서 4명 사망…52명 체포"', '뉴스1', 'https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=104&oid=421&aid=0005094290');
